name: simple_clean_navbar
description: The ultimate customizable bottom navigation bar for Flutter. Supports Floating, Side Rail, RTL, Dark Mode, Animations, and Immersive System UI.
version: 1.0.1
homepage: https://github.com/Nimakharraji/simple_clean_navbar
repository: https://github.com/Nimakharraji/simple_clean_navbar

topics:
  - navbar
  - bottom-navigation
  - side-rail
  - responsive-ui
  - animation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0